#!/usr/bin/env bash
# Bash script to automatically configure Ubuntu machine to requirements
sudo service nginx start
sudo sed -i "/server_name localhost;/a location /redirect_me { return 301 redirect_me.html; }" /etc/nginx/sites-enabled/default
