#!/usr/bin/env bash
# Bash script to automatically configure Ubuntu machine to requirements
sudo service nginx start
sed "/server_name localhost;/a location /redirect_me { return 301 localhost$requesturi; }/" /etc/nginx/sites-enabled/default
