#!/usr/bin/env bash
# Bash Script that displays To infinity and beyond, sleep 2, I am invincible!!!
trap "echo I am invincible!!!" SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
